apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: frontend-hpa # A unique name for your HPA object
spec:
  # This section defines which deployment the HPA should scale.
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: frontend-deployment # Must match the name of your frontend deployment

  # Define the scaling boundaries.
  minReplicas: 2   # Always keep at least 2 pods running for high availability.
  maxReplicas: 5   # Scale up to a maximum of 5 pods.

  # Define the metrics that will trigger scaling.
  metrics:
  - type: Resource
    resource:
      name: cpu
      # The target value that the HPA tries to maintain.
      target:
        type: Utilization
        # Scale up if the average CPU usage across all pods exceeds 80%.
        averageUtilization: 80
