apiVersion: v1
kind: PersistentVolume
metadata:
  name: cart-pv
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/mnt/data/cart" # This directory must exist on your Kubernetes node
